version: "{build}"

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

platform:
  - x86
  - x64

install:
  - ps: Install-Product node 7
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: node scripts/cibuild.js

artifacts:
  - path: 'out\Release\*.zip'

deploy:
  - provider: GitHub
    release: Yue $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '(placeholder)'
    auth_token:
      secure: txrp2eAOWw3fwVvYuRutmnek5xMtndPskyOMtu09vk9FeA5wdaQ2RGL/YAsCdIGH
    artifact: /.*\.zip/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true

# disable build and test pahses
build: off
test: off
