git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
osx_image: xcode7.3
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:webkit-team/ppa'
    packages:
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
      - libc6-dev-armhf-cross
      - linux-libc-dev-armhf-cross
      - binutils-aarch64-linux-gnu
      - libgtk-3-dev
      - libnotify-dev
      - webkit2gtk-4.0-dev

env:
  - TARGET_CPU=x64

matrix:
  include:
    - os: linux
      env:
        - TARGET_CPU=x86
    - os: linux
      env:
        - TARGET_CPU=arm
    - os: linux
      env:
        - TARGET_CPU=arm64

script: node ./scripts/cibuild.js
