git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - 8.2.1
os:
  - osx
osx_image: xcode8.3

env:
  - TARGET_CPU=x64

before_script:
  - export YUE_VERSION=$(git describe --always --tags)

script:
  - node ./scripts/cibuild.js --target-cpu=$TARGET_CPU

deploy:
  provider: releases
  api_key:
    secure: h2blB/R3MEtyB/ZdG6Z+kGduvBhPDmw4/tAweVVI/XfyI9kVa0clo497OUM6MUhFXP48CfNrj+5VVpLIryCQYObJ8raM47EPkTCYc/ikfICiNX6i7jIrPOM4otj4BshyAjPRYih20qXzxOMgT/e14UlPPY3t0rCYf0tmCkYoFO8ZjjG0h/JJe1TsVkNwV3MXCqFlRbFrnUeLGC/P9+cMlw8g5h67lEEWauazd1IVUAGKQrU7zw5IBwdoNFIIe1Z+3d9FcbpPeFwx8hxkLfP8/aysVDnTfg0H6bIDXsqpoAzGH3GBc1Tr67qgKgsgU8BP5iv2W03ZkHcfqKmwiDcHv2R1mOb199O19EuE2jb93R6dX4KrmkgRS/HQVcyyAdcYJ3nolwTgLwDtoXPGTBXunAoTWY6ZNf03nqSdHeN77HvKK2KkLt75+5ITh3KKnq7dbuiNbAG4gWWAtWh4CqpipOXqb0JUppwU5cA82vNAVeQPWhTg1YQu2ODNOzDpblyPurG1wvw9o1I62EW6QCxsmrfVPvMcrxIWv/wx37hbKxq+ptVwACmPOSpZIci8Azl2a3txy9EPYkSg+a+cYvuhsAyTOKCy2reuGoF16HaK9kfo/4obWdyKfHQObIgeAmT/3UQhc+d+GK1+1AMnysyDtaEJ14seHu4HdZQ/tdrK37k=
  file_glob: true
  file: out/Dist/*.zip
  skip_cleanup: true
  overwrite: true
  draft: true
  tag_name: ${YUE_VERSION}
  name: Yue ${YUE_VERSION}
  body: (placeholder)
  on:
    tags: true
