git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
osx_image: xcode7.3
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:webkit-team/ppa'
    packages:
      - xvfb
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
      - linux-libc-dev:i386
      - libc6-dev-armhf-cross
      - linux-libc-dev-armhf-cross
      - binutils-aarch64-linux-gnu
      - libgtk-3-dev
      - libnotify-dev
      - webkit2gtk-4.0-dev

env:
  - TARGET_CPU=x64

matrix:
  include:
    - os: linux
      env:
        - TARGET_CPU=x86
    - os: linux
      env:
        - TARGET_CPU=arm

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      xvfb-run node ./scripts/cibuild.js --target-cpu=$TARGET_CPU;
    else
      node ./scripts/cibuild.js --target-cpu=$TARGET_CPU;
    fi

deploy:
  provider: releases
  api_key:
    secure: kOBMmyflUZKqw6oXrXF3z0BuulaLSwwIte4TpqdWH9+aArGvjomxsRsthDDsa4MviAKLDQwjst8VBrfK0XD4Z/cydU9dUpC2aIPSLo+27kTMI18X3A9eBeaSU9DkT/bMhLtTIbH7vDUN+wlY8AH6j22W87gCP1skiHC8rsy6ySOl5toRVi+7RHWCTp9L+gl8jDaP0/+UsOD+2ElH15JaDbTXs3CR/b+jwFMMVp8iVnH5/52pAW2VdxRIEZ0KCEA+3rPdolEcGuTOmjMix1GRKq84LMlsasKo9vJ/jZ50RVBktcyKILvHqksgCk4UOAApe4y/GCftFUXQ8faYT5t3zfhpxfGKSrCzMQGV1/LmyLIPSsxoEph4yVVymvf65Mxa6gMLC7olHcKfE+2M0GzjFX5E4mTsapIzfHB+Q5pb9DOKAXugaUdecTNSnYHiLRnfpK5hZN3zssUTxe+ItGz+V+qxCyNNgeod39l7v6QAP8xg7SgLibtryFUNF/8RjY21iPufwRinVhjuD5o8L2iGamrsWU5PI8YRnW1if3Mpr7GBQXtjR4lVm+hoTi0hEyCGjQdmblamPeVhABu4a1bJqYwzEg9L6frCXkRTTZ17Y32WjwSoFve/XqYCSPglqXC3R1RRkDNH0bJhjj/lrYvxfGLdOkciCGI6PMQo1qsPqHA=
  file_glob: true
  file:
    - out/Release/node_yue_*.zip
  overwrite: true
  draft: true
  on:
    tags: true
