git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "8"
os:
  - osx
  - linux
osx_image: xcode8.3
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:webkit-team/ppa'
    packages:
      - xvfb
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
      - linux-libc-dev:i386
      - libc6-dev-armhf-cross
      - linux-libc-dev-armhf-cross
      - binutils-aarch64-linux-gnu
      - libgtk-3-dev
      - libnotify-dev
      - webkit2gtk-4.0-dev

env:
  - TARGET_CPU=x64

matrix:
  include:
    - os: linux
      env:
        - TARGET_CPU=x86
    - os: linux
      env:
        - TARGET_CPU=arm

before_script:
  - export YUE_VERSION=$(git describe --always --tags)

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      xvfb-run node ./scripts/cibuild.js --target-cpu=$TARGET_CPU;
    else
      node ./scripts/cibuild.js --target-cpu=$TARGET_CPU;
    fi

deploy:
  provider: releases
  api_key:
    secure: h2blB/R3MEtyB/ZdG6Z+kGduvBhPDmw4/tAweVVI/XfyI9kVa0clo497OUM6MUhFXP48CfNrj+5VVpLIryCQYObJ8raM47EPkTCYc/ikfICiNX6i7jIrPOM4otj4BshyAjPRYih20qXzxOMgT/e14UlPPY3t0rCYf0tmCkYoFO8ZjjG0h/JJe1TsVkNwV3MXCqFlRbFrnUeLGC/P9+cMlw8g5h67lEEWauazd1IVUAGKQrU7zw5IBwdoNFIIe1Z+3d9FcbpPeFwx8hxkLfP8/aysVDnTfg0H6bIDXsqpoAzGH3GBc1Tr67qgKgsgU8BP5iv2W03ZkHcfqKmwiDcHv2R1mOb199O19EuE2jb93R6dX4KrmkgRS/HQVcyyAdcYJ3nolwTgLwDtoXPGTBXunAoTWY6ZNf03nqSdHeN77HvKK2KkLt75+5ITh3KKnq7dbuiNbAG4gWWAtWh4CqpipOXqb0JUppwU5cA82vNAVeQPWhTg1YQu2ODNOzDpblyPurG1wvw9o1I62EW6QCxsmrfVPvMcrxIWv/wx37hbKxq+ptVwACmPOSpZIci8Azl2a3txy9EPYkSg+a+cYvuhsAyTOKCy2reuGoF16HaK9kfo/4obWdyKfHQObIgeAmT/3UQhc+d+GK1+1AMnysyDtaEJ14seHu4HdZQ/tdrK37k=
  file_glob: true
  file: out/Dist/*.zip
  skip_cleanup: true
  overwrite: true
  draft: true
  tag_name: ${YUE_VERSION}
  name: Yue ${YUE_VERSION}
  body: (placeholder)
  on:
    tags: true
